### ISSUE TITLE
Default Hosts entries

### ISSUE THREAD

**Issue by lima3w** [vgeyer/puppet-hosts#2]
I was looking at ways to adapt this to my current operation. I have a feature request:
Could you add to the hosts.erb lines that check if the puppet master is defined and add it if not, also the local fqdn/hostname? 
Example: 
if (@fqdn not in @servers array)
     @ipaddress @fqdn @hostname
end
if (@puppetmaster not in @servers array)
    @puppetmasterip @puppetmaster
end

**Comment by vgeyer** [comment]
Actually i am very busy, but feel free to create a pull request. :)

Victor
